msm: socinfo: Include init.h for __init definition
socinfo.h requires the __init definition:

arch/arm/mach-msm/include/mach/socinfo.h:60: error: expected '=',
',', ';', 'asm' or '__attribute__' before 'socinfo_init'

Change-Id: I54295cb5d7691fc9cdd920901edf0f51147efb4f
Signed-off-by: Stephen Boyd <sboyd@codeaurora.org>